//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLaptopNe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebPPEntities : DbContext
    {
        public WebPPEntities()
            : base("name=WebPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<ORDER_1> ORDER_1 { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<product_detail> product_detail { get; set; }
        public virtual DbSet<product_images> product_images { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<promotion> promotions { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<shipping> shippings { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
