//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLaptopNe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER_1()
        {
            this.order_details = new HashSet<order_details>();
            this.shippings = new HashSet<shipping>();
        }
    
        public int id { get; set; }
        public int promotion_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime created_at { get; set; }
        public decimal total_price { get; set; }
        public string note { get; set; }
        public string order_status { get; set; }
        public Nullable<decimal> shipping_fee { get; set; }
        public string shipping_method { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipping> shippings { get; set; }
        public virtual promotion promotion { get; set; }
    }
}
