//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLaptopNe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_detail
    {
        public int product_id { get; set; }
        public decimal weight { get; set; }
        public string cpu { get; set; }
        public string vga { get; set; }
        public string port { get; set; }
        public string ram { get; set; }
        public string storage { get; set; }
        public string webcam { get; set; }
        public string battery { get; set; }
        public string os { get; set; }
        public string screen_size { get; set; }
        public int stock_quantity { get; set; }
        public string warranty_period { get; set; }
        public string gpu { get; set; }
    
        public virtual product product { get; set; }
    }
}
