//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLaptopNe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public promotion()
        {
            this.ORDER_1 = new HashSet<ORDER_1>();
            this.promotion_programs = new HashSet<promotion_programs>();
            this.promotion_programs1 = new HashSet<promotion_programs>();
        }
    
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string promotion_name { get; set; }
        public System.DateTime start_day { get; set; }
        public System.DateTime end_day { get; set; }
        public Nullable<decimal> discount_percent { get; set; }
        public string promotion_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_1> ORDER_1 { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promotion_programs> promotion_programs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promotion_programs> promotion_programs1 { get; set; }
    }
}
