//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLaptopNe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public System.DateTime pickup_date { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string shipping_status { get; set; }
        public string address { get; set; }
        public string carrier { get; set; }
    
        public virtual ORDER_1 ORDER_1 { get; set; }
    }
}
